
import './globals.css'
import StyledComponentRegistry from "./registry"
import type { Metadata } from 'next'
import { DM_Sans } from 'next/font/google'
import Header from '@/components/Header'
const inter = DM_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: JSX.Element
}) {
  return (
    <html lang="en">
        <body className={inter.className}>
      <StyledComponentRegistry>
          <Header />
          {children}
        </StyledComponentRegistry>
        </body>
    </html>
  )
}
